plugins:
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-sequel

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.4.1
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: False

Metrics/ParameterLists:
  Max: 8

RSpec/NestedGroups:
  Max: 6

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10
