plugins:
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-sequel

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.4.1
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/ModuleLength:
  Max: 120

Metrics/ClassLength:
  Max: 120
  Exclude:
    - spec/support/pages/**/*

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: False

Metrics/ParameterLists:
  Max: 8

RSpec/NestedGroups:
  Max: 6

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 12
